---

- name: install and deply podman
  hosts: azure
  remote_user: administrador

  tasks:
    - name: Update and upgrade os
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: install podman
      become: true  
      apt:
        name: podman
        state: present

    - name: pull image
      containers.podman.podman_image:
        name: "docker.io/library/httpd:latest"
            
    - name: Build image
      containers.podman.podman_image:
        name: httpd
        path: /tmp/
        build:
          format: docker
    
    - name: push image
      containers.podman.podman_image:
        name: httpd
        path: /tmp/
        push: true
        username: cp2sfgacr
        password: ""  
        push_args:
          dest: "cp2sfgacr.azurecr.io/library/"

    - name: copy File index.html
      copy:
        src: /tmp/index/index.html
        dest: /tmp/index/

    - name: Deploy httpd   
      containers.podman.podman_container:
        name: httpd
        image: cp2sfgacr.azurecr.io/library/httpd
        state: started
        restart: true
        ports:
          - "8080:80"
        volume:
          - /tmp/index/:/usr/local/apache2/htdocs/


    - name: pull image backVote
      containers.podman.podman_image:
        name: mcr.microsoft.com/oss/bitnami/redis:6.0.8

    - name: pull image frontVote
      containers.podman.podman_image:
        name: mcr.microsoft.com/azuredocs/azure-vote-front:v1

    - name: Build image backVote
      containers.podman.podman_image:
        name: redis:6.0.8
        path: /tmp/
        build:
          format: docker

    - name: Build image frontVote
      containers.podman.podman_image:
        name: azure-vote-front:v1
        path: /tmp/
        build:
          format: docker

    - name: push image backVote
      containers.podman.podman_image:
        name: redis:6.0.8
        path: /tmp/
        push: true
        username: cp2sfgacr
        password: ""
        push_args:
          dest: "cp2sfgacr.azurecr.io/library/casopractico2/"

    - name: push image frontVote
      containers.podman.podman_image:
        name: azure-vote-front:v1
        path: /tmp/
        push: true
        username: cp2sfgacr
        password: ""
        push_args:
          dest: "cp2sfgacr.azurecr.io/library/casopractico2/"

    - name: install pip
      become: true
      apt:
        name: pip
        state: present
    
    - name: install prerequisites
      ansible.builtin.pip:
        name:
           - openshift
           - pyyaml
           - kubernetes

    - name: Create a k8s namespace
      kubernetes.core.k8s:
        kubeconfig: .kube/config
        name: testing
        api_version: v1
        kind: Namespace
        state: present
    - name: Create deploy
      kubernetes.core.k8s:
        kubeconfig: .kube/config
        state: present
        src: vote-app.yml
        namespace: testing
